name: Despliegue a Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar Surge
        run: npm install -g surge

      - name: Desplegar a Surge
        run: surge ./ https://mi-pagina-web.surge.sh --token ${{ secrets.SURGE_TOKEN }}
